-- ============================================
-- FORZA Waitlist — Supabase Table Setup
-- ============================================
-- Run this in: Supabase Dashboard → SQL Editor → New Query
-- Then click "Run" to execute.
-- ============================================

-- 1. Create the waitlist table
CREATE TABLE IF NOT EXISTS public.waitlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT,
  source TEXT DEFAULT 'coming_soon'
);

-- 2. Enable RLS (Row Level Security)
ALTER TABLE public.waitlist ENABLE ROW LEVEL SECURITY;

-- 3. Allow anyone to INSERT (so the public form can submit)
CREATE POLICY "Allow public inserts" ON public.waitlist
  FOR INSERT
  WITH CHECK (true);

-- 4. Only authenticated users (you) can read the data
CREATE POLICY "Only authenticated can read" ON public.waitlist
  FOR SELECT
  USING (auth.role() = 'authenticated');

-- 5. Add an index on email for fast duplicate checks
CREATE INDEX IF NOT EXISTS idx_waitlist_email ON public.waitlist (email);

-- Done! Your waitlist table is ready.
-- Go to Settings → API to copy your Project URL and anon key.
